site_name: Travaux dirigés EPUB
site_url: 'https://infologie.github.io/cours-epub/'
repo_name: 'infologie/cours-epub'
repo_url: 'https://github.com/infologie/cours-epub'
edit_uri: ''
site_author: Arthur Perret
site_description: 'Ressources pédagogiques EPUB – Arthur Perret 2020'
copyright: '© Arthur Perret 2020 CC BY'
nav:
    - Accueil: index.md
    - 1/ Sélection des contenus: 1Selection.md
    - 2/ Préparation de copie: 2PreparationDeCopie.md
    - 3/ Balisage: 3Balisage.md
    - 4/ Mise en forme: 4MiseEnForme.md
    - 5/ Métadonnées: 5Metadonnees.md
    - 6/ Assemblage: 6Assemblage.md
    - Exercices: Exercices.md
theme:
    name: 'material'
    custom_dir: 'theme'
    language: 'fr'
    palette:
        primary: 'teal'
        accent: 'green'
    font: false
    logo:
        icon: 'chrome_reader_mode'
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/arthurperret'
extra_css:
    - css/custom.css
